apiVersion: v1
kind: ServiceAccount
metadata:
  name: routing
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: get-nodes-for-routing
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: get-nodes-for-routing-bind
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: routing
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: get-nodes-for-routing
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name:  ospf-authentication-key
  namespace: kube-system
type: Opaque
data:
   authentication-key: dGVzdDEyMw==
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: bash-cni
  namespace: kube-system
  labels:
    k8s-app: bash-cni
spec:
  selector:
    matchLabels:
      k8s-app: bash-cni
  template:
    metadata:
      labels:
        k8s-app: bash-cni
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists   
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: routing
      priorityClassName: system-node-critical
      terminationGracePeriodSeconds: 0
      initContainers:
        - name: install
          imagePullPolicy: Always
          image: kp11/frr-cni-install:latest
          # For nft rules we have to be privileged
          securityContext:
            privileged: true
          env:
          - name: HOST_IP
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
          - name: AUTHENTICATION_KEY
            valueFrom:
              secretKeyRef:
                name: ospf-authentication-key
                key: authentication-key
                optional: false
          command:
            - bash
            - ./cni-startup.sh
          volumeMounts:
            # Used to configure FRR
            - name: workdir
              mountPath: "/etc/frr"
            # Used to install CNI
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
      containers:
        - name:  frr
          imagePullPolicy: IfNotPresent
          image: frrouting/frr
          securityContext:
            capabilities:
              add: [ "NET_BIND_SERVICE", "NET_ADMIN", "NET_RAW", "SYS_ADMIN" ]
          volumeMounts:
          - name: workdir
            mountPath: "/etc/frr"
      volumes:
        # Used to configure FRR
        - name: workdir
          emptyDir: {}
        # Used to install CNI
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d