apiVersion: v1
kind: Pod
metadata:
  name:  nettools
spec:
  terminationGracePeriodSeconds: 0
  tolerations:
    - effect: NoSchedule
      operator: Exists
    - effect: NoExecute
      operator: Exists 
  containers:
  - name:  nettools
    image: jrecord/nettools:latest
    command:
    - tail
    - -f
    - /dev/null
  nodeSelector:
    kubernetes.io/hostname: clear-k8s-01
---
apiVersion: v1
kind: Pod
metadata:
  name:  nettools2
spec:
  terminationGracePeriodSeconds: 0
  containers:
  - name:  nettools
    image: jrecord/nettools:latest
    command:
    - tail
    - -f
    - /dev/null